version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: islam-app-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: islamapp2024
      MONGO_INITDB_DATABASE: IslamApp
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - islam-app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: islam-app-backend
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - MongoDB__ConnectionString=mongodb://admin:islamapp2024@mongodb:27017/IslamApp?authSource=admin
      - MongoDB__DatabaseName=IslamApp
      - JWT__SecretKey=your-super-secret-jwt-key-change-this-in-production-2024
      - JWT__Issuer=IslamApp
      - JWT__Audience=IslamAppUsers
      - JWT__ExpirationDays=7
    depends_on:
      - mongodb
    networks:
      - islam-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:

networks:
  islam-app-network:
    driver: bridge 